[package]
name = "rustyline-async"
version = "0.1.0"
readme = "README.md"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
bytes = "0.5.4"
const_format = "0.2.22"
futures = "0.3.21"
futures_codec = "0.4.1"
libc = "0.2.121"
sluice = "0.5.5"
termion = "1.5.6"
thiserror = "1.0.30"

[workspace]
members = [ "examples/readline" ]

[package.metadata.nix]
build = true
toolchain = "nightly"
nativeBuildInputs = [ "cargo-edit" ]
