[package]
name = "rustyline-async"
version = "0.2.2"
license = "MIT OR Apache-2.0"
description = "A minimal readline with multiline and async support."
documentation = "https://docs.rs/rustyline-async"
repository = "https://github.com/zyansheep/rustyline-async"
readme = "README.md"
edition = "2021"

[dependencies]
crossterm = { version = "0.23.1", features = ["event-stream"] }
futures = "0.3.21"
pin-project = "1.0.10"
thingbuf = "0.1.1"
thiserror = "1.0.30"
unicode-segmentation = "1.9.0"
unicode-width = "0.1.9"

[workspace]
members = [
	"examples/readline",
	"examples/test-printing"
]

[features]
default = ["emacs"]
emacs = []

[package.metadata.nix]
build = true
toolchain = "stable"
nativeBuildInputs = [ "cargo-edit" ]
