[package]
name = "rustyline-async"
version = "0.2.4"
license = "Unlicense"
license-file = "UNLICENSE"
description = "A minimal readline with multiline and async support."
documentation = "https://docs.rs/rustyline-async"
repository = "https://github.com/zyansheep/rustyline-async"
readme = "README.md"
edition = "2021"

[dependencies]
crossterm = { version = "0.23.2", features = ["event-stream"] }
futures = "0.3.21"
pin-project = "1.0.10"
thingbuf = "0.1.3"
thiserror = "1.0.31"
unicode-segmentation = "1.9.0"
unicode-width = "0.1.9"

[dev-dependencies]
async-std = { version = "1.11.0", features = [ "unstable", "attributes" ] }
log = "0.4.16"
simplelog = "0.11.2"

[features]
default = ["emacs"]
emacs = []

[package.metadata.nix]
build = true
toolchain = "stable"
nativeBuildInputs = [ "cargo-edit" ]
