[package]
name = "rustyline-async"
version = "0.1.2"
readme = "README.md"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "A minimal readline with multiline and async support."

[dependencies]
crossterm = { version = "0.23.1", features = ["event-stream"] }
futures = "0.3.21"
thingbuf = "0.1.1"
thiserror = "1.0.30"

[workspace]
members = [ "examples/readline" ]

[features]

[package.metadata.nix]
build = true
toolchain = "nightly"
nativeBuildInputs = [ "cargo-edit" ]
